---
codecov:
  #
  # TODO: Place your codecov.io *BADGE* token here for private repositories
  badge_token: CODECOV_BADGE_TOKEN

codacy:
  #
  # TODO: Place your CODACY Project Id here.
  #       This is used for displaying your badge in public and private repos
  project_id: CODACY_BADGE_TOKEN

ght:
  template:
    url: https://github.com/sodre/ght-pypackage

  command_line_interface:
    - (*) Click
    - ( ) None

  license:
    - ( ) MIT
    - ( ) BSD
    - ( ) ISC
    - (*) Apache
    - ( ) GNUv3
    - ( ) Proprietary

cookiecutter:
  #
  # These were guess based on the repository information
  # You probably want to customize them.
  project_namespace: "{{ cookiecutter.github_organization.lower().replace(' ', '_').replace('-', '_') }}"
  project_slug: "{{ cookiecutter.project_repo.lower().replace(' ', '_').replace('-', '_').replace('.', '_').replace(cookiecutter.project_namespace+'_', '') }}"
  project_name: "{{ cookiecutter.project_namespace }}'s {{ cookiecutter.project_slug }}"

  #
  # These are likely correct...
  anaconda_organization: "{{ cookiecutter.github_organization }}"

  #
  # These should not be changed at the moment...
  noarch_python: y
  use_pytest: y
  add_pyup_badge: y
  version: 0.0.0

  #
  # These should probably be left alone. They came from github
  full_name: Patrick Sodré
  email: patrick@zero-ae.com
  github_username: sodre
  github_organization: zeroae
  project_repo: nifi.flowfile
  project_short_description: NiFi FlowFile Serializer
